### ISSUE TITLE
Little released version 9.10.0 and 10.1 is not released correctly

### ISSUE THREAD

**Issue by vtapadia** [LitleCo/litle-sdk-for-java#50]
The components pom.xml is released incorrectly which makes the download of the component from maven an issue.

For 9.3.3, the pom was released as **[litle-sdk-for-java-9.3.3.pom](https://dl.bintray.com/litlesdk/maven/com/litle/litle-sdk-for-java/9.3.3/)** (which is correct)
But for release 9.10.0 and 10.1 it was released as **[pom.xml](https://dl.bintray.com/litlesdk/maven/com/litle/litle-sdk-for-java/9.10.0/)** . This makes the download to maven based projects fail.

Can you please release this properly?

**Comment by brianarnold789** [comment]
Maven repository has been fixed for 9.10.0, version 10.0 is not release for GA, so I will not be changing the pom file at this time.

**Comment by vtapadia** [comment]
Thanks for the quick response.

**Comment by vtapadia** [comment]
While updating, I just noticed that the pom is still not correct.

The file name should be litle-sdk-for-java-9.10.0.pom and not litle-sdk-for-java-9.10.0.xml

Can you please correct this?

**Comment by brianarnold789** [comment]
.pom file should have the correct extension now
